[project]
name = "mcp-server-papers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.3.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.20.0",
    "pytest>=8.4.2",
    "python-dotenv>=1.2.1",
    "ruff>=0.14.3",
]
